domains:
  grafana: "grafana.{cloud}-{region}.streaming.datastax.com/"
  prometheus: "prometheus.{cloud}-{region}.streaming.datastax.com/"

clusters:
  - name: "dev.aws.astrastreaming-datastax-us-east-2-dataplane"
    env: "dev"
    cloud: "aws"
    region: "useast2"
    project: "datastax"
  - name: "dev.aws.astrastreaming-public-us-east-2-dataplane"
    env: "dev"
    cloud: "aws"
    region: "useast2"
    project: "public"
  - name: "dev.azure.astrastreaming-public-westus2-dataplane"
    env: "dev"
    cloud: "azure"
    region: "westus2"
    project: "public"
  - name: "dev.gcp.astrastreaming-public-eu-west-4-dataplane"
    env: "dev"
    cloud: "gcp"
    region: "euwest4"
    project: "public"
  - name: "dev.gcp.astrastreaming-public-us-east-1-dataplane"
    env: "dev"
    cloud: "gcp"
    region: "useast1"
    project: "public"
  - name: "dev.gcp.astrastreaming-public-us-east-4-dataplane"
    env: "dev"
    cloud: "gcp"
    region: "useast4"
    project: "public"
  - name: "staging.aws.astrastreaming-datastax-us-east-2-dataplane"
    env: "staging"
    cloud: "aws"
    region: "useast2"
    project: "datastax"
  - name: "staging.aws.astrastreaming-public-us-east-2-dataplane"
    env: "staging"
    cloud: "aws"
    region: "useast2"
    project: "public"
  - name: "staging.azure.astrastreaming-public-westus2-dataplane"
    env: "staging"
    cloud: "azure"
    region: "westus2"
    project: "public"
  - name: "staging.gcp.astrastreaming-public-us-east1-dataplane"
    env: "staging"
    cloud: "gcp"
    region: "useast1"
    project: "public"
  - name: "staging.gcp.astrastreaming-public-us-east4-dataplane"
    env: "staging"
    cloud: "gcp"
    region: "useast4"
    project: "public"
  - name: "prod.azure.astrastreaming-public-australiaeast-dataplane"
    env: "prod"
    cloud: "azure"
    region: "australiaeast"
    project: "public"
  - name: "prod.azure.astrastreaming-public-eastus-dataplane"
    env: "prod"
    cloud: "azure"
    region: "eastus"
    project: "public"
  - name: "prod.azure.astrastreaming-public-westeurope-dataplane"
    env: "prod"
    cloud: "azure"
    region: "westeurope"
    project: "public"
  - name: "prod.azure.astrastreaming-public-westus2-dataplane"
    env: "prod"
    cloud: "azure"
    region: "westus2"
    project: "public"
  - name: "prod.gcp.astrastreaming-koddi-prod-us-east4-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "useast4"
    project: "koddi"
  - name: "prod.gcp.astrastreaming-macquarie-nonprod-australia-southeast1-dataplane"
    env: "nonprod"
    cloud: "gcp"
    region: "australiasoutheast1"
    project: "macquarie"
  - name: "prod.gcp.astrastreaming-macquarie-prod-australia-southeast1-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "australiasoutheast1"
    project: "macquarie"
  - name: "prod.gcp.astrastreaming-public-australia-southeast1-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "australiasoutheast1"
    project: "public"
  - name: "prod.gcp.astrastreaming-public-eu-west-3-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "europewest3"
    project: "public"
  - name: "prod.gcp.astrastreaming-public-europe-west1-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "europewest1"
    project: "public"
  - name: "prod.gcp.astrastreaming-public-us-central1-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "uscentral1"
    project: "public"
  - name: "prod.gcp.astrastreaming-public-us-east1-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "useast1"
    project: "public"
  - name: "prod.gcp.astrastreaming-public-us-east4-dataplane"
    env: "prod"
    cloud: "gcp"
    region: "useast4"
    project: "public"
  - name: "prod.aws.astrastreaming-public-us-east-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast1"
    project: "public"
  - name: "prod.aws.astrastreaming-public-us-east-2-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast2"
    project: "public"
  - name: "prod.aws.astrastreaming-public-us-west-2-dataplane"
    env: "prod"
    cloud: "aws"
    region: "uswest2"
    project: "public"
  - name: "prod.aws.astrastreaming-quera-int-us-east-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast1"
    project: "quera"
  - name: "prod.aws.astrastreaming-quera-prod-us-east-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast1"
    project: "quera"
  - name: "prod.azure.astrastreaming-koddi-dev-eastus-dataplane"
    env: "prod"
    cloud: "azure"
    region: "eastus"
    project: "koddi"
  - name: "prod.azure.astrastreaming-koddi-prod-centralus-dataplane"
    env: "prod"
    cloud: "azure"
    region: "centralus"
    project: "koddi"
  - name: "prod.azure.astrastreaming-koddi-prod-eastus-dataplane"
    env: "prod"
    cloud: "azure"
    region: "eastus"
    project: "koddi"
  - name: "prod.azure.astrastreaming-koddi-uat-centralus-dataplane"
    env: "prod"
    cloud: "uat"
    region: "centralus"
    project: "koddi"
  - name: "prod.azure.astrastreaming-koddi-uat-eastus-dataplane"
    env: "uat"
    cloud: "azure"
    region: "eastus"
    project: "koddi"
    
  - name: "prod.azure.astrastreaming-public-australiaeast-dataplane"
    env: "prod"
    cloud: "azure"
    region: "australiaeast"
    project: "public"
  - name: "prod.azure.astrastreaming-public-eastus-dataplane"
    env: "prod"
    cloud: "azure"
    region: "eastus"
    project: "public"
  - name: "prod.aws.astrastreaming-koddi-prod-eu-west-3-dataplane"
    env: "prod"
    cloud: "aws"
    region: "euwest3"
    project: "koddi"
  - name: "prod.aws.astrastreaming-koddi-prod-us-east-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast1"
    project: "koddi"
  - name: "prod.aws.astrastreaming-koddi-prod-us-west-2-dataplane"
    env: "prod"
    cloud: "aws"
    region: "uswest2"
    project: "koddi"
  - name: "prod.aws.astrastreaming-koddi-uat-eu-west-2-dataplane"
    env: "uat"
    cloud: "aws"
    region: "euwest2"
    project: "koddi"
  - name: "prod.aws.astrastreaming-koddi-uat-us-east-1-dataplane"
    env: "uat"
    cloud: "aws"
    region: "useast1"
    project: "koddi"
  - name: "prod.aws.astrastreaming-portbase-dev-eu-west-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "euwest1"
    project: "portbase"
  - name: "prod.aws.astrastreaming-portbase-prod-eu-central-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "eucentral1"
    project: "portbase"
  - name: "prod.aws.astrastreaming-portbase-prod-eu-west-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "euwest1"
    project: "portbase"
  - name: "prod.aws.astrastreaming-public-ap-south-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "apsouth1"
    project: "public"
  - name: "prod.aws.astrastreaming-public-ap-southeast-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "apsoutheast1"
    project: "public"
  - name: "prod.aws.astrastreaming-public-ap-southeast-2-dataplane"
    env: "prod"
    cloud: "aws"
    region: "apsoutheast2"
    project: "public"
  - name: "prod.aws.astrastreaming-public-eu-central-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "eucentral1"
    project: "public"
  - name: "prod.aws.astrastreaming-public-eu-west-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "euwest1"
    project: "public"
  - name: "prod.aws.astrastreaming-datastax-us-east-2-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast2"
    project: "datastax"
  - name: "prod.aws.astrastreaming-klarna-prod-ap-southeast-2-dataplane"
    env: "prod"
    cloud: "aws"
    region: "apsoutheast2"
    project: "klarna"
  - name: "prod.aws.astrastreaming-klarna-prod-eu-west-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "euwest1"
    project: "klarna"
  - name: "prod.aws.astrastreaming-klarna-prod-us-east-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast1"
    project: "klarna"
  - name: "prod.aws.astrastreaming-koddi-ap-southeast-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "apsoutheast1"
    project: "koddi"
  - name: "prod.aws.astrastreaming-koddi-dev-us-east-1-dataplane"
    env: "prod"
    cloud: "aws"
    region: "useast1"
    project: "koddi"
  - name: "prod.aws.astrastreaming-koddi-prod-eu-west-2-dataplane"
    env: "prod"
    cloud: "aws"
    region: "euwest2"
    project: "koddi"
  - name: "prod.aws.astrastreaming-koddi-prod-eu-west-3-dataplane"
    env: "prod"
    cloud: "aws"
    region: "euwest3"
    project: "koddi"

